aliases:
  - &restore-cache
    keys:
      - dependencies-feat/website-{{ checksum "package.json" }}
      # Fallback in case checksum fails
      - dependencies-feat/website-

  - &save-cache
    paths:
      - node_modules
      - example/node_modules
      - website/node_modules
    key: dependencies-feat/website-{{ checksum "package.json" }}

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: yarn install
      - run: cd example && yarn install && yarn build && cd ..
      - run: cd website && yarn install && yarn build && cd ..
      - save-cache: *save-cache
      - run: yarn run lint
      - run: yarn run flow
      - run: yarn test -- --coverage

  # test-e2e:
