version: 2
defaults: &defaults
  docker:
    - image: circleci/node:6.10.3
  working_directory: ~/linaria
jobs:
  install-dependencies:
    <<: *defaults
    steps:
        - checkout
        - attach_workspace:
            at: ~/linaria
        - restore_cache:
            name: Restore node_modules cache
            keys:
            - v1-node-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-node-{{ .Branch }}-
            - v1-node-
        - run:
            name: Install Dependencies
            command: yarn install
        - save_cache:
            name: Save yarn cache
            key: v1-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
            paths:
            - .cache/yarn
        - save_cache:
            name: Save node_modules cache
            key: v1-node-{{ .Branch }}-{{ checksum "yarn.lock" }}
            paths:
            - node_modules/
        - restore_cache:
            name: Restore website node_modules cache
            keys:
            - v1-website-node-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-website-node-{{ .Branch }}-
            - v1-website-node-
        - run:
            name: Install Dependencies Website
            command: yarn install --cwd website
        - save_cache:
            name: Save website/node_modules cache
            key: v1-website-node-{{ .Branch }}-{{ checksum "yarn.lock" }}
            paths:
            - website/node_modules/
        - save_cache:
            name: Save website yarn cache
            key: v1-website-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
            paths:
            - website/.cache/yarn
        - persist_to_workspace:
            root: .
            paths: .
  lint-and-flow:
      <<: *defaults
      steps:
        - attach_workspace:
            at: ~/linaria
        - run: |
            yarn run lint
            yarn run flow
  unit-tests:
      <<: *defaults
      steps:
        - attach_workspace:
            at: ~/linaria
        - run: |
            yarn test -- --coverage
            cat ./coverage/lcov.info | ./node_modules/.bin/codecov
        - store_artifacts:
            path: coverage
            destination: coverage
  integration-tests:
      <<: *defaults
      steps:
        - attach_workspace:
            at: ~/linaria
        - run: |
            bash .circleci/install-chrome-deps.sh
            yarn run test:integration:ci
        - store_artifacts:
            path: website/__integration-tests__/__image_snapshots__/__diff_output__
            destination: website-snapshot-diffs
  build-and-lint-website:
      <<: *defaults
      steps:
        - attach_workspace:
            at: ~/linaria
        - run: cd website && yarn run build:all && cd ..
        - run: cd website && yarn run lint-css && cd ..
workflows:
  version: 2
  build-and-test:
    jobs:
      - install-dependencies
      - lint-and-flow:
          requires:
            - install-dependencies
      - unit-tests:
          requires:
            - install-dependencies
      - integration-tests:
          requires:
            - install-dependencies
      - build-and-lint-website:
          requires:
            - install-dependencies
